### ISSUE TITLE
Testing the swiss4 block I encountered two problems (branch logging)

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#145]
First problem:
```

2024-10-18 00:11:44,618 - testrunner - ERROR - 'set' object is not subscriptable: Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\swiss_to_db.py", line 63, in <module>
    main(args.swiss_zip_file, args.database, args.clean_database,args.referencing)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\swiss_to_db.py", line 28, in main
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\swiss_to_db.py", line 37, in main
    resolve_all_references_and_embeddings(con, classes)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 859, in resolve_all_references_and_embeddings
    clazz_by_name[interesting_element_names[i]] = clazz
                  ~~~~~~~~~~~~~~~~~~~~~~~~~^^^


```
block:
```

       {
    "block": "swiss4",
    "scripts": [
        {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "swiss_to_db.py", "args": "--log=%%log%% d:/swiss4.zip %%dir%%/swiss-import.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/swiss-import.duckdb %%dir%%/netex-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/swiss-import.duckdb %%dir%%/netex-database.duckdb %%dir%%/%%block%%-netex.xml"},
        {"script": "tool_netex_check_assertions.py", "args": "--log=%%log%% ./aux_test_input/swiss-assertions.txt %%dir%%/%%block%%-netex.xml"},
        {"script": "tool_netex_stats.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml"},
        {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml %%dir%%/netex2-database.duckdb"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb ServiceJourney random %%dir%%/sj.xml"},
        {"script": "netex_db_to_gtfs.py", "args": "--log=%%log%% %%dir%%/netex-database.duckdb %%dir%%/%%block%%-gtfs.zip"},
        {"script": "tool_simple_gtfs_validator.py", "args": "--log=%%log%% %%dir%%/%%block%%-gtfs.zip"},
        {"script": "gtfs_show_map.py", "args": "--log=%%log%% %%dir%%/%%block%%-gtfs.zip %%dir%%/%%block%%-map.html"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb Line random %%dir%%/line.xml"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/swiss-import.duckdb ServiceJourney random %%dir%%/sj1.xml"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex-database.duckdb ServiceJourney random %%dir%%/sj2.xml"}
        ]
  },



```
file: 
[swiss4.zip](https://github.com/user-attachments/files/17424706/swiss4.zip)

Later in the process it before found no agency.txt after the gtfs export. However, those might be a later error following from the first one. I was on the way to check it, then I enforced a harder handling of errors and now I am stuck there.

**Comment by ue71603** [comment]
Outdated
