### ISSUE TITLE
swiss4 failing even more fundamentally

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#171]
I used the new master and it failed during epip_db_to_db.py

error:
```

C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py --log=swiss4/run.log d:/aux_testing_processing/swiss4/swiss-import.duckdb d:/aux_testing_processing/swiss4/netex-database.duckdb 
epip_line_memory
2024-12-06 11:31:44,259 - testrunner - ERROR - 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 58, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 42, in main
    epip_line_memory(source_database_file, target_database_file, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 58, in epip_line_memory
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 64, in epip_line_memory
    lines: List[Line] = load_local(read_con, Line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 90, in load_local
    cur = db.con
          ^^^^^^
AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con'

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 61, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 58, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 42, in main
    epip_line_memory(source_database_file, target_database_file, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 58, in epip_line_memory
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 64, in epip_line_memory
    lines: List[Line] = load_local(read_con, Line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 90, in load_local
    cur = db.con
          ^^^^^^
AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con'

Process finished with exit code 1

```

Script sequence see:  
https://github.com/skinkie/reference/issues/170

**Comment by ue71603** [comment]
Also all other conversions in the regression fail: python tool_script_runner.py ./scripts/scripts_regression.txt run.log all something in the pickle implementation does not work with the current installation I have.  Did you use new libraries?

**Comment by ue71603** [comment]
now new problem:

```

2024-12-06 17:35:49,757 - testrunner - ERROR - a bytes-like object is required, not 'str': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 63, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    epip_line_memory(source_db, target_db, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 53, in epip_line_memory
    lines: List[Line] = load_local(db_read, Line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 109, in load_local
    obj = db.serializer.unmarshall(xml, type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\pickleserializer.py", line 19, in unmarshall
    return pickle.loads(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

**Comment by skinkie** [comment]
Last error has just been resolved.

**Comment by ue71603** [comment]
just refreshed from origin and still does not work....

```

2024-12-06 20:08:03,572 - testrunner - ERROR - a bytes-like object is required, not 'str': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 63, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    epip_line_memory(source_db, target_db, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 51, in epip_line_memory
    lines: List[Line] = load_local(db_read, Line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 109, in load_local
    obj = db.serializer.unmarshall(xml, type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\pickleserializer.py", line 19, in unmarshall
    return pickle.loads(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 66, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 63, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    epip_line_memory(source_db, target_db, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 51, in epip_line_memory
    lines: List[Line] = load_local(db_read, Line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 109, in load_local
    obj = db.serializer.unmarshall(xml, type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\pickleserializer.py", line 19, in unmarshall
    return pickle.loads(obj)
           ^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

Process finished with exit code 1
```

**Comment by skinkie** [comment]
@ue71603 I am positive netex_to_db, epip_db_to_db, and epip_db_to_xml results in a file.

**Comment by ue71603** [comment]
It does now. and the swiss4 transform from CH NeTEx to EPIP produces a valid xml file.
