### ISSUE TITLE
error in related explorer

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#175]
In swissmikro regression test:

```

C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py --log=swissmikro/run.log d:/aux_testing_processing/swissmikro/netex2-database.duckdb ServiceJourney random d:/aux_testing_processing/swissmikro/sj.xml 
2024-12-07 12:57:18,019 - testrunner - ERROR - 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 180, in <module>
    fetch(args.netex, args.object_type, args.object_filter, args.output)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 126, in fetch
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 138, in fetch
    objs = load_local(con, getattr(netex, object_type))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 90, in load_local
    cur = db.con
          ^^^^^^
AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con'

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 183, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 180, in <module>
    fetch(args.netex, args.object_type, args.object_filter, args.output)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 126, in fetch
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\related_explorer.py", line 138, in fetch
    objs = load_local(con, getattr(netex, object_type))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 90, in load_local
    cur = db.con
          ^^^^^^
AttributeError: 'duckdb.duckdb.DuckDBPyConnection' object has no attribute 'con'

Process finished with exit code 1

```

looks a bit similiar to the previous problem in the other files. Don't they use the same code base?

**Comment by ue71603** [comment]
python tool_script_runner.py ./scripts/scripts_regression.txt run.log swissmikro

**Comment by skinkie** [comment]
The updated code that is share is actually the cause of the problem, because the calling code is not updated. Doing that now.

**Comment by skinkie** [comment]
Please check the result. It has some other cool improvements.

**Comment by ue71603** [comment]
related_explorer itself does not break. It doesn't export what it should on swissmikro. But that is a different issue.
