### ISSUE TITLE
Problem in processing an exported servicejourney with related_explorer (from swissmikro example)

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#179]
sj.xml was exported with related_explorer.py

Then read with netex_to_db.py
epip_db_to_db.py then stops with error (see below)

What is the problem:
* related_explorer.py not exporting everything that is needed?
* netex_to_db.py not the right program to load sj.xml?
* problem in epip_db_to_db.py?

error message in epip_db_to_db.py:
```

2024-12-08 16:02:23,125 - testrunner - ERROR - 'NoneType' object has no attribute 'route_ref_or_route_view': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 64, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 50, in main
    epip_service_journey_generator(source_db, target_db, generator_defaults, None)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 454, in epip_service_journey_generator
    write_generator(db_write, ServiceJourney, query(db_read), True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 393, in write_generator
    for a in _prepare3(generator, objectname):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 369, in _prepare3
    for obj in generator3:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 448, in query
    yield process(sj, db_read, db_write, generator_defaults)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 429, in process
    recover_line_ref(sj, service_journey_pattern, db_read)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 359, in recover_line_ref
    if service_journey_pattern.route_ref_or_route_view is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'route_ref_or_route_view'

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 67, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 64, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 50, in main
    epip_service_journey_generator(source_db, target_db, generator_defaults, None)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 454, in epip_service_journey_generator
    write_generator(db_write, ServiceJourney, query(db_read), True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 393, in write_generator
    for a in _prepare3(generator, objectname):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 369, in _prepare3
    for obj in generator3:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 448, in query
    yield process(sj, db_read, db_write, generator_defaults)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 429, in process
    recover_line_ref(sj, service_journey_pattern, db_read)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 359, in recover_line_ref
    if service_journey_pattern.route_ref_or_route_view is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'route_ref_or_route_view'

Process finished with exit code 1

```

Script sequence
```

{
    "block": "swissmikro",
    "scripts": [
        {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "gtfs_import_to_db.py", "args": "d:/input/swiss_mikro.zip %%dir%%/gtfs-import.duckdb --log=%%log%% "},
        {"script": "gtfs_convert_to_db.py", "args": "--log=%%log%% %%dir%%/gtfs-import.duckdb %%dir%%/netex-import.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb %%dir%%/%%block%%-netex.xml"},
        {"script": "tool_netex_stats.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml"},
        {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml %%dir%%/netex2-database.duckdb"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb ServiceJourney random %%dir%%/sj.xml"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb Line random %%dir%%/line.xml"},
        {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/sj.xml %%dir%%/netex3-database.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/netex3-database.duckdb %%dir%%/netex4-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/netex3-database.duckdb %%dir%%/netex4-database.duckdb %%dir%%/%%block%%-sj-netex.xml"}
        ]
  },
```

**Comment by ue71603** [comment]
[sj.zip](https://github.com/user-attachments/files/18052741/sj.zip)

**Comment by ue71603** [comment]
I guess the main problem is that sj.xml is incomplete and not valid. So the real problem is: https://github.com/skinkie/reference/issues/179
