### ISSUE TITLE
nl examples don't produce GTFS with my script

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#189]
Hi Stefan

My script produces empty gtfs files.... How should they be done?
```

      {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "dutch_to_db.py", "args": "d:/input/NeTEx_TESO_TESO_20241112_20241112.xml.gz %%dir%%/nl-import.duckdb"},
        {"script": "netex_db_to_gtfs.py", "args": "--log=%%log%% %%dir%%/nl-import.duckdb %%dir%%/%%block%%-teso-gtfs.zip"},

```

**Comment by ue71603** [comment]
So how did you test NeTEx->GTFS, when not with this example?

**Comment by ue71603** [comment]
new script:
```

        {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "netex_to_db.py", "args": "d:/input/NeTEx_TESO_TESO_20241112_20241112.xml.gz %%dir%%/nl-import.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/nl-import.duckdb %%dir%%/netex-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/nl-import.duckdb %%dir%%/netex-database.duckdb %%dir%%/%%block%%-teso-netex.xml"},
        {"script": "netex_to_db.py", "args": "%%dir%%/%%block%%-teso-netex.xml %%dir%%/nl-gtfs.duckdb"},
 
```       {"script": "netex_db_to_gtfs.py", "args": "--log=%%log%% %%dir%%/nl-gtfs.duckdb %%dir%%/%%block%%-teso-gtfs.zip"},

better but missing routes.txt, feed_info.txt, agency.txt:

[nl-teso-gtfs.zip](https://github.com/user-attachments/files/18096565/nl-teso-gtfs.zip)

**Comment by ue71603** [comment]
[nl-teso-gtfs.zip](https://github.com/user-attachments/files/18096581/nl-teso-gtfs.zip)

**Comment by skinkie** [comment]
@ue71603 you don't find new issues ;-) They are already defined at: #134

**Comment by skinkie** [comment]
Going to implement #133

**Comment by skinkie** [comment]
@ue71603 first steps, but this gives me now a validated TESO GTFS. Please test.

**Comment by ue71603** [comment]
program died in epit_db_to_xml 
```

024-12-13 17:44:45,730 - testrunner - ERROR - Catalog Error: Table with name embedding does not exist!
Did you mean "embedded"?
LINE 1: ...LECT DISTINCT class, ref, version FROM embedding;
                                                  ^: Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 247, in <module>
    export_epip_network_offer(args.original, args.target, args.output)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 221, in export_epip_network_offer
    members=GeneralFrameMembersRelStructure(choice=other_referenced_objects.generator()) if other_referenced_objects.has_value() else None
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 77, in has_value
    self.first = self.value.__next__()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 234, in fetch_references_classes_generator
    cur2.execute(query)
duckdb.duckdb.CatalogException: Catalog Error: Table with name embedding does not exist!
Did you mean "embedded"?
LINE 1: ...LECT DISTINCT class, ref, version FROM embedding;
                                                  ^

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 250, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 247, in <module>
    export_epip_network_offer(args.original, args.target, args.output)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 221, in export_epip_network_offer
    members=GeneralFrameMembersRelStructure(choice=other_referenced_objects.generator()) if other_referenced_objects.has_value() else None
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_xml.py", line 77, in has_value
    self.first = self.value.__next__()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 234, in fetch_references_classes_generator
    cur2.execute(query)
duckdb.duckdb.CatalogException: Catalog Error: Table with name embedding does not exist!
Did you mean "embedded"?
LINE 1: ...LECT DISTINCT class, ref, version FROM embedding;

```

**Comment by ue71603** [comment]
now more basic errors. create a new issue
