### ISSUE TITLE
While running

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#2]
Gtfs2NeTEx.py I got  the following error with the just downloaded flixbus file

C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\GtfsNeTEx.py 
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\GtfsNeTEx.py", line 15, in <module>
    from callsprofile import CallsProfile
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\callsprofile.py", line 5, in <module>
    from netex import ServiceJourney, StopPointInJourneyPattern, ServiceJourneyPattern, PointsInJourneyPatternRelStructure, \
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 1, in <module>
    from .abstract_capabilities_structure import AbstractCapabilitiesStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\abstract_capabilities_structure.py", line 3, in <module>
    from .capability_general_interaction_structure import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\capability_general_interaction_structure.py", line 7, in <module>
    @dataclass(kw_only=True)
TypeError: dataclass() got an unexpected keyword argument 'kw_only'

**Comment by ue71603** [comment]
solved
