### ISSUE TITLE
All basic transform break in epip_db_to_db.py still the copytable function

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#200]
Perhaps you check the script sequence. If you use anything else, I need to know.

I guess we really should look at the library versions.

### python tool_script_runner.py ./scripts/scripts_regression.txt run.log swissmikro

```

C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py --log=swissmikro/run.log d:/aux_testing_processing/swissmikro/netex-import.duckdb d:/aux_testing_processing/swissmikro/netex-database.duckdb 
CREATE TABLE IF NOT EXISTS embedded (parent_class varchar(64) NOT NULL, parent_id varchar(64) NOT NULL, parent_version varchar(64) not null, class varchar(64) not null, id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, path TEXT NOT NULL, PRIMARY KEY (parent_class, parent_id, parent_version, class, id, version, ordr));
CREATE TABLE IF NOT EXISTS referencing (parent_class varchar(64) NOT NULL, parent_id varchar(64) NOT NULL, parent_version varchar(64) not null, class varchar(64) not null, ref varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, PRIMARY KEY (parent_class, parent_id, parent_version, class, ref, version, ordr));
CREATE TABLE IF NOT EXISTS AvailabilityCondition (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS DestinationDisplay (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Direction (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Line (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Notice (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS NoticeAssignment (id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id, version));
CREATE TABLE IF NOT EXISTS Operator (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS PassengerStopAssignment (id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id, version));
CREATE TABLE IF NOT EXISTS RouteLink (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS RoutePoint (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ScheduledStopPoint (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ServiceJourney (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ServiceJourneyPattern (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS StopPlace (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS VehicleType (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
2024-12-15 16:56:01,511 - testrunner - ERROR - IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 30004): Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 68, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    copy_table(source_db, target_db,[Notice, ScheduledStopPoint], clean=True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 587, in copy_table
    db_write.con.execute(f"ATTACH IF NOT EXISTS '{db_read.database_file}' AS db_read (READ_ONLY);")
duckdb.duckdb.IOException: IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 30004)

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 71, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 68, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    copy_table(source_db, target_db,[Notice, ScheduledStopPoint], clean=True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 587, in copy_table
    db_write.con.execute(f"ATTACH IF NOT EXISTS '{db_read.database_file}' AS db_read (READ_ONLY);")
duckdb.duckdb.IOException: IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 30004)


```
python tool_script_runner.py ./scripts/scripts_regression.txt run.log nl

```

C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py --log=nl/run.log d:/aux_testing_processing/nl/nl-import.duckdb d:/aux_testing_processing/nl/netex-database.duckdb 
CREATE TABLE IF NOT EXISTS embedded (parent_class varchar(64) NOT NULL, parent_id varchar(64) NOT NULL, parent_version varchar(64) not null, class varchar(64) not null, id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, path TEXT NOT NULL, PRIMARY KEY (parent_class, parent_id, parent_version, class, id, version, ordr));
CREATE TABLE IF NOT EXISTS referencing (parent_class varchar(64) NOT NULL, parent_id varchar(64) NOT NULL, parent_version varchar(64) not null, class varchar(64) not null, ref varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, PRIMARY KEY (parent_class, parent_id, parent_version, class, ref, version, ordr));
CREATE TABLE IF NOT EXISTS AvailabilityCondition (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS DestinationDisplay (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Direction (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Line (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS Notice (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS NoticeAssignment (id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id, version));
CREATE TABLE IF NOT EXISTS Operator (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS PassengerStopAssignment (id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id, version));
CREATE TABLE IF NOT EXISTS RouteLink (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS RoutePoint (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ScheduledStopPoint (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ServiceJourney (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS ServiceJourneyPattern (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS StopPlace (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS VehicleType (id varchar(64) NOT NULL, version varchar(64), object BINARY NOT NULL, last_modified TIMESTAMP NOT NULL, PRIMARY KEY (id));
2024-12-15 17:02:23,979 - testrunner - ERROR - IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 7436): Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 68, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    copy_table(source_db, target_db,[Notice, ScheduledStopPoint], clean=True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 587, in copy_table
    db_write.con.execute(f"ATTACH IF NOT EXISTS '{db_read.database_file}' AS db_read (READ_ONLY);")
duckdb.duckdb.IOException: IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 7436)

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 71, in <module>
    raise e
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 68, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 47, in main
    copy_table(source_db, target_db,[Notice, ScheduledStopPoint], clean=True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 587, in copy_table
    db_write.con.execute(f"ATTACH IF NOT EXISTS '{db_read.database_file}' AS db_read (READ_ONLY);")
duckdb.duckdb.IOException: IO Error: File is already open in 
C:\Users\ue71603\AppData\Local\Programs\Python\Python312\python.exe (PID 7436)

Process finished with exit code 1

```

**Comment by skinkie** [comment]
I think we need a small test, if this is windows specific. It seems that I am trusting that duckdb can have access to the same file considering it was opened read only. 

https://duckdb.org/docs/connect/concurrency.html

**Comment by ue71603** [comment]
works with the new version.
