### ISSUE TITLE
Transformation GTFS BadenWürrtemberg gives error 

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#52]
File:
https://www.mobidata-bw.de/dataset/soll-fahrplandaten-baden-wurttemberg/resource/ed68f96a-b965-4e65-ba85-39316b09cbea

Process:

```
del C:/Users/ue71603/MG_Daten/conversion/bw/*.duckdb
python gtfs_import_to_db.py C:/Users/ue71603/MG_Daten/conversion/bw/bwgesamt.zip  C:/Users/ue71603/MG_Daten/conversion/bw/gtfs-import.duckdb
python gtfs_convert_to_db.py C:/Users/ue71603/MG_Daten/conversion/bw/gtfs-import.duckdb C:/Users/ue71603/MG_Daten/conversion/bw/netex-import.duckdb
python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/bw/netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/bw/netex-import-epip.duckdb
python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/bw/netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/bw/netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/bw/bwnetex.xml.gz
del C:/Users/ue71603/MG_Daten/conversion/bw/*.duckdb

```

In  
`python gtfs_convert_to_db.py C:/Users/ue71603/MG_Daten/conversion/bw/gtfs-import.duckdb C:/Users/ue71603/MG_Daten/conversion/bw/netex-import.duckdb
`
the following error occured:

```
Operator 315
StopArea 1192
ScheduledStopPoint 58273
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1266, in <module>
    main(args.gtfs, args.database)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1256, in main
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1257, in main
    gtfs.database(con)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1205, in database
    stop_places, passenger_stop_assignments = self.getStopPlaces()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 345, in getStopPlaces
    with self.conn.cursor() as cur:
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 386, in getStopPlaces
    stop_place = stop_places[getId(StopPlace, self.codespace, parent_stations[i])]
                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'NVBW:StopPlace:at-49-1349_Parent'

```

also here a lot of ScheduledStopPoint don't have coordinates:
`ScheduledStopPoint ch:1:ScheduledStopPoint:8780099-0-Gen does not have a location.`

Will this create a problem later on in the process?

**Comment by ue71603** [comment]
Some problem happens also for SNCF: https://eu.ftp.opendatasoft.com/sncf/gtfs/export-intercites-gtfs-last.zip


```
(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python gtfs_convert_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_gtfs/gtfs-im
port.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_gtfs/netex-import.duckdb
Line 23
Codespace 1
DataSource 1
Version 1
Operator 2
StopArea 153
ScheduledStopPoint 182
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1266, in <module>
    main(args.gtfs, args.database)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1256, in main
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1257, in main
    gtfs.database(con)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 1205, in database
    stop_places, passenger_stop_assignments = self.getStopPlaces()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 345, in getStopPlaces
    with self.conn.cursor() as cur:
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\gtfs_convert_to_db.py", line 386, in getStopPlaces
    stop_place = stop_places[getId(StopPlace, self.codespace, parent_stations[i])]
                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'S:StopPlace:StopArea-OCE87391003'

```

**Comment by skinkie** [comment]
> also here a lot of ScheduledStopPoint don't have coordinates: `ScheduledStopPoint ch:1:ScheduledStopPoint:8780099-0-Gen does not have a location.`
> 
> Will this create a problem later on in the process?

If the stops are actually in use in the timetable, _and_ there are no quays with coordinates. No valid GTFS can be made.

**Comment by ue71603** [comment]
Ok, so I hope there are..... the KeyError is still a problem....  and it seems to exist for multiple files.

**Comment by skinkie** [comment]
I'll prioritize the 'get locations from quays/stopplaces'.

**Comment by skinkie** [comment]
@ue71603 Rootcause for the stopplaces was that the stops were iterated over in the wrong order due to null not being sorted at the top.
