### ISSUE TITLE
Swiss NeTEX --> EPIP  fails in epip_db_to_xml.py

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#53]
[swiss.zip](https://github.com/user-attachments/files/16333579/swiss.zip)

command sequence:

```
del C:/Users/ue71603/MG_Daten/conversion/swiss/*.duckdb
python swiss_to_db.py C:/Users/ue71603/MG_Daten/conversion/swiss/swiss.zip C:/Users/ue71603/MG_Daten/conversion/swiss/swiss-import.duckdb
python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/swiss/swiss-import.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss/netex-import-epip.duckdb
python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/swiss/swiss-import.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss/netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss/netex.xml
python netex_stats.py C:/Users/ue71603/MG_Daten/conversion/swiss/netex.xml
del C:/Users/ue71603/MG_Daten/conversion/swiss/*.duckdb

```

fails in 

```
(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/swiss/swiss-import.du
ckdb C:/Users/ue71603/MG_Daten/conversion/swiss/netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss/netex.xml
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_xml.py", line 243, in <module>
    export_epip_network_offer(args.original, args.target, args.output)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_xml.py", line 155, in export_epip_network_offer
    default_locale: LocaleStructure = project(list(all_locales)[0], LocaleStructure) if len(all_locales) > 0 else None
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\utils.py", line 5, in project
    attributes = {x: y for x, y in obj.__dict__.items() if x in list(clazz.__dataclass_fields__.keys())}
                                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?

```

probably you fixed this in the epip_to_epip already

**Comment by skinkie** [comment]
Trying to reproduce this.
