### ISSUE TITLE
Working on demand responsive NeTEx data

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#56]
We also have demand responsive data:

NeTEx: https://opentransportdata.swiss/dataset/da04e7c7-aa9c-47fd-8a78-085f46061f29/resource/3ead1130-144c-463a-8228-d6964fe94aec/download/ge16614_01_diva_odv_all_prod_20240722090104.xml.zip

https://opentransportdata.swiss/de/dataset/gtfsflex

Next construction site  :-) 

command sequence:

```
del C:/Users/ue71603/MG_Daten/conversion/swiss_drt/*.duckdb
python swiss_to_db.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/swiss_drt.zip C:/Users/ue71603/MG_Daten/conversion/swiss_drt/swiss-import.duckdb
python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/swiss-import.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex-import-epip.duckdb
python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/swiss-import.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss_drt//netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex.xml
python netex_stats.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex.xml
del C:/Users/ue71603/MG_Daten/conversion/swiss_drt/*.duckdb
python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex.xml  C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex-database.duckdb
python netex_db_to_gtfs.py C:/Users/ue71603/MG_Daten/conversion/swiss_drt/netex-database.duckdb C:/Users/ue71603/MG_Daten/conversion/swiss_drt/gtfs_output.zip
del C:/Users/ue71603/MG_Daten/conversion/swiss_drt/*.duckdb

```
error in epip_db_to_db.py : 

```
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_db.py", line 51, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_db.py", line 40, in main
    epip_site_frame_memory(source_database_file, target_database_file, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\transformers\epip.py", line 114, in epip_site_frame_memory
    with sqlite3.connect(read_database) as read_con:
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\transformers\epip.py", line 120, in epip_site_frame_memory
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\transformers\epip.py", line 202, in epip_site_frame_memory
    project_location_4326(stop_place.centroid.location, generator_defaults)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'

```

Perhaps it is, because those ScheduledStopPoints represent areas and therefore don't have a normal location.

**Comment by skinkie** [comment]
There are multiple problems here.
 1. The first is obviously the trust that there is a centroid on a quay, this is resolved, we can now fall back to the StopPlace centroid as last resort.
 2. The second problem is more troublesome. I consider the situation below as something that is on multiple levels wrong. Why is there a ScheduledStopPoint and a StopPlace that is completely empty (even advertises that it is the wrong type). Why doesn't the PassengerStopAssignment directly assigns the ScheduledStopPoint to the FlexibleStopPlace?
 ```
    <PassengerStopAssignment id="ch:1:PassengerStopAssignment:ch:1:StopPlaceCollectionPoint:1" version="any" order="1">
      <ScheduledStopPointRef ref="ch:1:StopPlaceCollectionPoint:1-0-Gen" version="any" />
      <StopPlaceRef ref="ch:1:StopPlaceCollectionPoint:1" version="any" />
    </PassengerStopAssignment>

    <ScheduledStopPoint id="ch:1:StopPlaceCollectionPoint:1-0-Gen" version="any" />

    <StopPlace id="ch:1:StopPlaceCollectionPoint:1" version="any">
      <Name lang="de">Gais Klinik</Name>
      <ShortName lang="de">Gais Klinik</ShortName>
      <PrivateCode>1</PrivateCode>
      <ParentZoneRef ref="ch:1:FlexibleArea:Publicar_Appenzell" version="any" />
      <placeTypes>
        <TypeOfPlaceRef ref="ch:1:TypeOfPlace:drtCollectionPoint" version="any" />
      </placeTypes>
    </StopPlace>
    
    <FlexibleStopPlace id="ch:1:FlexibleStopPlace:Publicar_Appenzell" version="any">
      <ShortName>29</ShortName>
      <areas>
        <FlexibleArea id="ch:1:FlexibleArea:Publicar_Appenzell" version="any">
          <Name lang="de">Publicar Appenzell</Name>
          <ShortName>29</ShortName>
          <members>
            <ScheduledStopPointRef ref="ch:1:StopPlaceCollectionPoint:1-0-Gen" version="any" />
          </members>
          <gml:Polygon gml:id="Area29" srsName="EPSG:4326">
            <gml:exterior>
              <gml:LinearRing>
                <gml:pos>9.3890941 47.3906506</gml:pos>
                <gml:pos>9.3907571 47.3888783</gml:pos>
                <gml:pos>9.3919909 47.3870478</gml:pos>
                <gml:pos>9.3902099 47.3868953</gml:pos>
                <gml:pos>9.3864441 47.384934</gml:pos>
                <gml:pos>9.383837 47.3853771</gml:pos>
```
