### ISSUE TITLE
SNCF file problem 

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#57]
[export-intercites-netex-last.zip](https://github.com/user-attachments/files/16377598/export-intercites-netex-last.zip)

comannd sequence:
```

del C:/Users/ue71603/MG_Daten/conversion/sncf_netex/*.duckdb
python swiss_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb
python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex-import-epip.duckdb
python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex.xml
python netex_stats.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex.xml
del C:/Users/ue71603/MG_Daten/conversion/sncf_netex/*.duckdb

```
fails in  swiss_to_db.py:
```
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\swiss_to_db.py", line 4, in <module>
    from anyintodbnew import  get_interesting_classes, setup_database, open_netex_file, insert_database
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\anyintodbnew.py", line 6, in <module>
    from netex import JourneyPart
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 87, in <module>
    from .access_space import AccessSpace
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_space.py", line 3, in <module>
    from .access_space_version_structure import AccessSpaceVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_space_version_structure.py", line 7, in <module>
    from .stop_place_space_version_structure import StopPlaceSpaceVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\stop_place_space_version_structure.py", line 6, in <module>
    from .site_entrances_rel_structure import SiteEntrancesRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\site_entrances_rel_structure.py", line 5, in <module>
    from .entrance import Entrance
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\entrance.py", line 3, in <module>
    from .site_entrance_version_structure import SiteEntranceVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\site_entrance_version_structure.py", line 9, in <module>
    from .site_component_version_structure import SiteComponentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\site_component_version_structure.py", line 6, in <module>
    from .equipment_places_rel_structure import EquipmentPlacesRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\equipment_places_rel_structure.py", line 5, in <module>
    from .equipment_place import EquipmentPlace
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\equipment_place.py", line 3, in <module>
    from .equipment_place_version_structure import EquipmentPlaceVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\equipment_place_version_structure.py", line 5, in <module>
    from .equipments_rel_structure import EquipmentsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\equipments_rel_structure.py", line 4, in <module>
    from .access_vehicle_equipment import AccessVehicleEquipment
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_vehicle_equipment.py", line 3, in <module>
    from .access_vehicle_equipment_version_structure import AccessVehicleEquipmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_vehicle_equipment_version_structure.py", line 5, in <module>
    from .actual_vehicle_equipment_version_structure import ActualVehicleEquipmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\actual_vehicle_equipment_version_structure.py", line 5, in <module>
    from .accessibility_assessment import AccessibilityAssessment
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\accessibility_assessment.py", line 3, in <module>
    from .accessibility_assessment_versioned_child_structure import AccessibilityAssessmentVersionedChildStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\accessibility_assessment_versioned_child_structure.py", line 8, in <module>
    from .suitabilities_rel_structure import SuitabilitiesRelStructure
    from .suitability import Suitability
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\suitability.py", line 4, in <module>
    from .suitability_versioned_child_structure import SuitabilityVersionedChildStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\suitability_versioned_child_structure.py", line 4, in <module>
    from .user_need_versioned_child_structure import UserNeedVersionedChildStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\user_need_versioned_child_structure.py", line 8, in <module>
    from .psychosensory_need_enumeration import PsychosensoryNeedEnumeration
ModuleNotFoundError: No module named 'netex.psychosensory_need_enumeration'
```

**Comment by skinkie** [comment]
Maybe some files were not added... let me check.

**Comment by skinkie** [comment]
Done!
