### ISSUE TITLE
probably nextex not exported right

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#62]
Or should I be able to do it now on my own:

```
python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-
import.duckdb
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 33, in <module>
    main(args.netex, args.database, args.clean_database)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 15, in main                         
    with sqlite3.connect(database) as con:                                                                                   
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 16, in main                         
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netexio\dbaccess.py", line 356, in get_interesting_classes
    import netex
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 760, in <module>
    from .data_object_delivery import DataObjectDelivery
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\data_object_delivery.py", line 3, in <module>
    from .data_object_delivery_structure import DataObjectDeliveryStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\data_object_delivery_structure.py", line 6, in <module>
    from .data_objects_rel_structure import DataObjectsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\data_objects_rel_structure.py", line 6, in <module>
    from .general_version_frame_structure import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\general_version_frame_structure.py", line 405, in <module>
    from .resource_frame import ResourceFrame
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\resource_frame.py", line 3, in <module>
    from .resource_frame_version_frame_structure import ResourceFrameVersionFrameStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\resource_frame_version_frame_structure.py", line 28, in <module>
    from .vehicle_equipmen_profiles_in_frame_rel_structure import VehicleEquipmenProfilesInFrameRelStructure
ModuleNotFoundError: No module named 'netex.vehicle_equipmen_profiles_in_frame_rel_structure'

```

**Comment by skinkie** [comment]
I think this is resolved, please confirm.

**Comment by ue71603** [comment]
no, was not solved.
```


(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-
import.duckdb
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 6, in <module>                            
    from netexio.dbaccess import get_interesting_classes, setup_database, open_netex_file, insert_database                         
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netexio\dbaccess.py", line 12, in <module>                      
    from mro_attributes import list_attributes                                                                                     
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\mro_attributes.py", line 8, in <module>                         
    import netex                                                                                                                   
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 80, in <module>                        
    from .access_right_parameter_assignment import AccessRightParameterAssignment                                                  
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment.py", line 3, in <module>
    from .access_right_parameter_assignment_version_structure import AccessRightParameterAssignmentVersionStructure                                   
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment_version_structure.py", line 14, in <module>
    from .dynamic_distance_matrix_element import DynamicDistanceMatrixElement
    from .dynamic_distance_matrix_element_version_structure import DynamicDistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\dynamic_distance_matrix_element_version_structure.py", line 3, in <module>
    from .distance_matrix_element_version_structure import DistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\distance_matrix_element_version_structure.py", line 9, in <module>
    from .geographical_structure_factors_rel_structure import GeographicalStructureFactorsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factors_rel_structure.py", line 4, in <module>
    from .geographical_structure_factor import GeographicalStructureFactor
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor.py", line 3, in <module>
    from .geographical_structure_factor_version_structure import GeographicalStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor_version_structure.py", line 9, in <module>
    from .priceable_object_version_structure import FareStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\priceable_object_version_structure.py", line 78, in <module>
    from .fare_table_columns_rel_structure import FareTableColumnsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\fare_table_columns_rel_structure.py", line 8, in <module>
    from .object_refs_rel_structure import ObjectRefsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\object_refs_rel_structure.py", line 34, in <module>
    from .booking_debit_ref import BookingDebitRef
ModuleNotFoundError: No module named 'netex.booking_debit_ref'
(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex-import-epip
.duckdb
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_db.py", line 10, in <module>
    from anyintodbnew import setup_database, get_interesting_classes
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\anyintodbnew.py", line 6, in <module>
    from netex import JourneyPart
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 80, in <module>
    from .access_right_parameter_assignment import AccessRightParameterAssignment
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment.py", line 3, in <module>
    from .access_right_parameter_assignment_version_structure import AccessRightParameterAssignmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment_version_structure.py", line 14, in <module>
    from .dynamic_distance_matrix_element import DynamicDistanceMatrixElement
    from .dynamic_distance_matrix_element_version_structure import DynamicDistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\dynamic_distance_matrix_element_version_structure.py", line 3, in <module>
    from .distance_matrix_element_version_structure import DistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\distance_matrix_element_version_structure.py", line 9, in <module>
    from .geographical_structure_factors_rel_structure import GeographicalStructureFactorsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factors_rel_structure.py", line 4, in <module>
    from .geographical_structure_factor import GeographicalStructureFactor
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor.py", line 3, in <module>
    from .geographical_structure_factor_version_structure import GeographicalStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor_version_structure.py", line 9, in <module>
    from .priceable_object_version_structure import FareStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\priceable_object_version_structure.py", line 78, in <module>
    from .fare_table_columns_rel_structure import FareTableColumnsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\fare_table_columns_rel_structure.py", line 8, in <module>
    from .object_refs_rel_structure import ObjectRefsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\object_refs_rel_structure.py", line 34, in <module>
    from .booking_debit_ref import BookingDebitRef
ModuleNotFoundError: No module named 'netex.booking_debit_ref'
(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python epip_db_to_xml.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex-import-epi
p.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex.xml
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\epip_db_to_xml.py", line 16, in <module>
    from netexio.dbaccess import load_local
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netexio\dbaccess.py", line 12, in <module>
    from mro_attributes import list_attributes
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\mro_attributes.py", line 8, in <module>
    import netex
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 80, in <module>
    from .access_right_parameter_assignment import AccessRightParameterAssignment
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment.py", line 3, in <module>
    from .access_right_parameter_assignment_version_structure import AccessRightParameterAssignmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\access_right_parameter_assignment_version_structure.py", line 14, in <module>
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\dynamic_distance_matrix_element.py", line 3, in <module>
    from .dynamic_distance_matrix_element_version_structure import DynamicDistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\dynamic_distance_matrix_element_version_structure.py", line 3, in <module>
    from .distance_matrix_element_version_structure import DistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\distance_matrix_element_version_structure.py", line 9, in <module>
    from .geographical_structure_factors_rel_structure import GeographicalStructureFactorsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factors_rel_structure.py", line 4, in <module>
    from .geographical_structure_factor import GeographicalStructureFactor
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor.py", line 3, in <module>
    from .geographical_structure_factor_version_structure import GeographicalStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\geographical_structure_factor_version_structure.py", line 9, in <module>
    from .priceable_object_version_structure import FareStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\priceable_object_version_structure.py", line 78, in <module>
    from .fare_table_columns_rel_structure import FareTableColumnsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\fare_table_columns_rel_structure.py", line 8, in <module>
    from .object_refs_rel_structure import ObjectRefsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\object_refs_rel_structure.py", line 34, in <module>
ModuleNotFoundError: No module named 'netex.booking_debit_ref'

```

**Comment by skinkie** [comment]
Can you remove the netex folder and then do a `git reset`?

**Comment by ue71603** [comment]
I think the problem is not the download side as the file does not exist in master in github:
![image](https://github.com/user-attachments/assets/957fe176-30e3-4f6b-b8a2-5a8675d74389)

**Comment by skinkie** [comment]
Going to regenerate.

**Comment by ue71603** [comment]
Not working:

```
(venv) PS C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test> python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-
import.duckdb
Traceback (most recent call last):
    main(args.netex, args.database, args.clean_database)
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 15, in main
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex_to_db.py", line 16, in main
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netexio\dbaccess.py", line 373, in get_interesting_classes
    general_frame_members = netex.GeneralFrameMembersRelStructure.__dataclass_fields__['choice'].metadata['choices']
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'netex' has no attribute 'GeneralFrameMembersRelStructure'
(v

```

**Comment by skinkie** [comment]
Not an issue here. 

```
rm -r netex
git reset -- netex
git checkout -- netex
```

**Comment by ue71603** [comment]
not working

**Comment by skinkie** [comment]
Can't help you then. Clean checkout please.

**Comment by ue71603** [comment]
Doing it.
