### ISSUE TITLE
Completly clean clone also does not work

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#63]
*  clone repository
* switch to gtfs-netex-test
* create project in pycharm in that folder (using python 3.9)
* pip install --update pip
* pip install -requirements.txt
* running:  python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb

Did run  into exactly the same error

```
(venv) PS C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test> python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/sncf_netex/netex-import-epi
p.duckdb
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 10, in <module>
    from anyintodbnew import setup_database, get_interesting_classes
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\anyintodbnew.py", line 6, in <module>
    from netex import JourneyPart
ImportError: cannot import name 'JourneyPart' from 'netex' (unknown location)
(venv) PS C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test> python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex
-import.duckdb
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_to_db.py", line 33, in <module>
    main(args.netex, args.database, args.clean_database)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_to_db.py", line 15, in main
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_to_db.py", line 16, in main
    classes = get_interesting_classes()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 373, in get_interesting_classes
    general_frame_members = netex.GeneralFrameMembersRelStructure.__dataclass_fields__['choice'].metadata['choices']
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'netex' has no attribute 'GeneralFrameMembersRelStructure'
```

**Comment by skinkie** [comment]
I am currently retracing your steps.  Do you notice that in your previous bug your error presented itself in netex_to_db.py while here in epip_db_to_db.py? So currently importing...

**Comment by skinkie** [comment]
This does not give me any errors. What I am surprised with is the epip duckdb file size.
The only difference I notice is that you are running python 3.9, and I am at 3.12.
```
  502  cd /tmp/
  503  git clone https://github.com/skinkie/reference
  504  cd reference/gtfs-netex-test/
  506  python -m venv venv
  507  source venv/bin/activate
  508  pip install -r requirements.txt 
  509  scp skinkie@192.168.5.32:/tmp/*zip /tmp/.
  510  python netex_to_db.py /tmp/export-intercites-netex-last.zip /tmp/sncf.duckdb
  513  python epip_db_to_db.py /tmp/sncf.duckdb /tmp/sncf-epip.duckdb
  514  ls -l /tmp/sncf*
(venv) skinkie@thinkpad /tmp/reference/gtfs-netex-test $ ls -l /tmp/sncf*
-rw-r--r-- 1 skinkie skinkie 414199808 Aug  2 17:54 /tmp/sncf.duckdb
-rw-r--r-- 1 skinkie skinkie   9187328 Aug  2 17:57 /tmp/sncf-epip.duckdb
```

**Comment by ue71603** [comment]
the error is still in 
python netex_to_db.py C:/Users/ue71603/MG_Daten/conversion/sncf_netex/export-intercites-netex-last.zip C:/Users/ue71603/MG_Daten/conversion/sncf_netex/sncf_netex-import.duckdb

**Comment by ue71603** [comment]
if I wrote anything else, then that was my mistake.


do I need to do a xsdata generate at some point (would mean you fixed the problem). Ok I try to switch to python 12.

**Comment by skinkie** [comment]
No, xsdata generate is done by me, and included in the repository. The only reason we need xsdata 'my branch' in the repository is to have the _generators_ to work. I am unable to reproduce you issue... maybe teams?

**Comment by ue71603** [comment]
worked on other machine with a very clean installation. from python on up.. work there for the time being.

**Comment by skinkie** [comment]
I am very interested if you find the cause.
