### ISSUE TITLE
Issue with Swiss data

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#65]
Question:
                <StopPointInJourneyPattern id="OPENOV:StopPointInJourneyPattern:bee9eb39-1" version="any" order="1">
                  <ScheduledStopPointRef ref="ch:1:ScheduledStopPoint:8500010:12" versionRef="any"/>
                  <noticeAssignments>
                    <NoticeAssignment id="ch:1:NoticeAssignment:ch_1_ServiceJourney_ch_1_sjyid_100001_1089-001_9103WY.j24_16_1" version="any" order="1">
                      <NoticeRef ref="ch:1:Notice:A__BA" versionRef="any"/>
                    </NoticeAssignment>
                    <NoticeAssignment id="ch:1:NoticeAssignment:ch_1_ServiceJourney_ch_1_sjyid_100001_1089-001_9103WY.j24_16_1" version="any" order="2">
                      <NoticeRef ref="ch:1:Notice:A__WR" versionRef="any"/>
                    </NoticeAssignment>
                  </noticeAssignments>

is this valid or not? same id, but different order.
```

(.venv) PS D:\development\github\reference\gtfs-netex-test> python netex_to_db.py D:\development/conversion/swiss/netex.xml  D:\development/conversion/swiss/netex-database.duckdb

CREATE TABLE IF NOT EXISTS ZoneProjection (id varchar(64) NOT NULL, version varchar(64) NOT NULL, ordr integer, object text NOT NULL, PRIMARY KEY (id, version));    
<NoticeAssignment xmlns="http://www.netex.org.uk/netex" xmlns:gml="http://www.opengis.net/gml/3.2" id="ch:1:NoticeAssignment:ch_1_ServiceJourney_ch_1_sjyid_100001_1089-001_9103WY.j24_16_1" version="any" order="2"><NoticeRef ref="ch:1:Notice:A__WR" versionRef="any"/></NoticeAssignment>
Traceback (most recent call last):
  File "D:\development\github\reference\gtfs-netex-test\netex_to_db.py", line 33, in <module>
    main(args.netex, args.database, args.clean_database)
  File "D:\development\github\reference\gtfs-netex-test\netex_to_db.py", line 15, in main
    with sqlite3.connect(database) as con:
  File "D:\development\github\reference\gtfs-netex-test\netex_to_db.py", line 23, in main
    insert_database(con, classes, sub_file)
  File "D:\development\github\reference\gtfs-netex-test\netexio\dbaccess.py", line 473, in insert_database
    cur.execute(sql_insert_object, (id, version, order, xml,))
duckdb.duckdb.ConstraintException: Constraint Error: Duplicate key "id: ch:1:NoticeAssignment:ch_1_ServiceJourney_ch_1_sjyid_100001_1089-001_9103WY.j24_16_1, version: any" violates primary key constraint. If this is an unexpected constraint violation please double check with the known index limitations section in our documentation (https://duckdb.org/docs/sql/indexes).
(.venv) PS D:\development\github\reference\gtfs-netex-test>


```

**Comment by skinkie** [comment]
Yes, that is why I required to get TimetabledPassingTime with order :-) So they really did a id+version+oder as unique element, also for other element.

**Comment by skinkie** [comment]
```
<xsd:unique name="NoticeAssignment_UniqueBy_Id_Version_Order">
        <xsd:annotation>
                <xsd:documentation>Every [NoticeAssignment Id + Version +order] must be unique within document.</xsd:documentation>
        </xsd:annotation>
        <xsd:selector xpath=".//netex:NoticeAssignment"/>
        <xsd:field xpath="@id"/>
        <xsd:field xpath="@version"/>
        <xsd:field xpath="@order"/>
</xsd:unique>
```
I think the schema made `order` optional...

**Comment by skinkie** [comment]
NoticeAssignment should not have been imported, because it was part of another object.

**Comment by ue71603** [comment]
Generated objects always should have unique id => to be discussed with MENTZ

**Comment by skinkie** [comment]
As discussed, this all uncovered some fundamental problems as well.

**Comment by ue71603** [comment]
we close it here.
