### ISSUE TITLE
Trenitalia

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#78]
Warning says to post it

```
C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py:355: UserWarning: No uic_operating_periods available, submit this example to github
  warnings.warn("No uic_operating_periods available, submit this example to github")
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 53, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 43, in main
    epip_service_journey_generator(source_database_file, target_database_file, generator_defaults, None)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 427, in epip_service_journey_generator
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 441, in epip_service_journey_generator
    service_calendar = get_service_calendar(day_types, uic_operating_periods, day_type_assignments, generator_defaults)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 357, in get_service_calendar
    from_date = min([uic.from_operating_day_ref_or_from_date.to_datetime() for uic in uic_operating_periods])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() iterable argument is empty
```

```
    {
    "block": "trenitalia",
    "scripts": [
        {"script": "clean_tmp", "args": ["./aux_test_processing"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_input/trenitalia.zip ./aux_test_processing/netex-import.duckdb"]},
        {"script": "epip_db_to_db.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb"]},
        {"script": "epip_db_to_xml.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb ./aux_test_processing/trenitalia-netex.xml"]},
        {"script": "aux_assertions.py", "args": ["./aux_test_input/general-netex-assertions.txt ./aux_test_processing/trenitalia-netex.xml"]},
        {"script": "aux_netex_stats.py", "args": ["./aux_test_processing/trenitalia-netex.xml"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_processing/trenitalia-netex.xml ./aux_test_processing/netex-database.duckdb"]},
        {"script": "netex_db_to_gtfs.py", "args": ["./aux_test_processing/netex-database.duckdb ./aux_test_processing/trenitalia-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["./aux_test_processing/trenitalia-gtfs.zip ./aux_test_processing/trenitalia-map.html"]}
        ]
  },
```
[trenitalia.zip](https://github.com/user-attachments/files/16742192/trenitalia.zip)

**Comment by skinkie** [comment]
This is _caused_ by the recent change that prevents the creating objects in the database that are embedded. In this case operatingPeriods are embedded within a (single) ServiceCalendar. Hence the UicOperatingPeriod is not available anymore as single instance in the database. This is similar to how Quays have to be recovered, since they are part of a StopPlace but are not available directly.

Now since get_service_calendar (in this case) get parts of an existing service calendar as input this fails. It wouldn't have failed if the data was created from contentValidityContitions for example. The positive side could be: reuse the entire ServiceCalendar. But the more fundamental thing how should this be handled for these embedded objects?
