### ISSUE TITLE
SOLEA example not working

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#82]
for id='SOLEA:ServiceJourney:5313906-E_2024-internet-Semaine-01-'

warnings:
```
2C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py:307: UserWarning: SOLEA:DayType:S_2023-internet-Semaine-07-1101100 does not have any valid days
  warnings.warn(f"{day_type_id} does not have any valid days")

```

```
 ServiceJourney 3536Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "epip_db_to_db.py", line 55, in <module>
    main(args.source, args.target)
  File "epip_db_to_db.py", line 45, in main
    epip_service_journey_generator(source_database_file, target_database_file, generator_defaults, None)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 431, in epip_service_journey_generator
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 437, in epip_service_journey_generator
    write_generator(write_con, ServiceJourney, query(read_con), True)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 277, in write_generator
    for a in _prepare3(generator, objectname):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\dbaccess.py", line 253, in _prepare3
    for obj in generator3:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 424, in query
    yield process(sj, read_database, write_database, generator_defaults)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 408, in process
    service_journey_ac_to_day_type(sj, availability_conditions, day_types, uic_operating_periods, day_type_assignments)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 301, in service_journey_ac_to_day_type
    day_type_id = acs[0].id.replace('AvailabilityCondition', 'DayType')
                  ~~~^^^
IndexError: list index out of range

Execution time: 2407.535975456238 seconds

Script epip_db_to_db.py returned an error. Terminating the block of scripts: solea

Process finished with exit code 0

```

[solea.zip](https://github.com/user-attachments/files/16949747/solea.zip)

pls check, what goes wrong here.

**Comment by skinkie** [comment]
@ue71603 is it correct this is a GTFS source?

**Comment by skinkie** [comment]
Did you get this error too?
```
/mnt/storage/home/skinkie/Sources/references/gtfs-netex-test/transformers/epip.py:307: UserWarning: SOLEA:DayType:S_2023-internet-Semaine-07-1101100 does not have any valid days
  warnings.warn(f"{day_type_id} does not have any valid days")
/mnt/storage/home/skinkie/Sources/references/gtfs-netex-test/transformers/epip.py:307: UserWarning: SOLEA:DayType:S_2023-internet-Semaine-07-1000000 does not have any valid days
  warnings.warn(f"{day_type_id} does not have any valid days")
```

**Comment by skinkie** [comment]
@ue71603 
trips.txt
```
92-775,E_2024-internet-Samedi-04-,5321424-E_2024-internet-Samedi-04-,"PORTE JEUNE",0,864637,920055,2,2
```

calendar.txt does not contain _E_2024-internet-Samedi-04-_.

**Comment by skinkie** [comment]
We can now _gracefully_ process it. But in my opinion it is not correct, because it should actually show the invalid reference?

**Comment by ue71603** [comment]
yes. it was a GTFS and yes, I got the warnings.

I will check it now beforehand (and inform them about the problem)

**Comment by ue71603** [comment]
asked them to make better data.
