### ISSUE TITLE
Using next for netex does crate problems

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#9]
- I used the flixbus example  https://transport.data.gouv.frresources/11681?id=11681&locale=en
- added an feed_info.txt
- emptied the folder netex
- downloaded next  from github
- regenerated `xsdata generate C:\Users\ue71603\MG_Daten\github\NeTEx1\xsd/NeTEx_publication.xsd -p netex --kw-only --compound-fields `
- run `GtfsNeTEx.py`

Then I get a problem:

```
C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\GtfsNeTEx.py 
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\GtfsNeTEx.py", line 15, in <module>
    from callsprofile import CallsProfile
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\callsprofile.py", line 5, in <module>
    from netex import ServiceJourney, StopPointInJourneyPattern, ServiceJourneyPattern, PointsInJourneyPatternRelStructure, \
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\__init__.py", line 1, in <module>
    from netex.ne_tex_publication import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\ne_tex_publication.py", line 4, in <module>
    from netex.netex_framework.netex_payload_framework import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\__init__.py", line 1, in <module>
    from netex.netex_framework.netex_payload_framework import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_payload_framework.py", line 3, in <module>
    from netex.netex_framework.netex_frames.netex_composite_frame_version import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_frames\__init__.py", line 1, in <module>
    from netex.netex_framework.netex_frames.netex_common_frame_version import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_frames\netex_common_frame_version.py", line 2, in <module>
    from netex.netex_framework.netex_responsibility.netex_version_frame_version import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_responsibility\__init__.py", line 5, in <module>
    from netex.netex_framework.netex_responsibility.netex_alternative_text_version import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_responsibility\netex_alternative_text_version.py", line 3, in <module>
    from netex.netex_framework.netex_responsibility.netex_relationship import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_responsibility\netex_relationship.py", line 4, in <module>
    from netex.netex_framework.netex_frames.netex_composite_frame_version import (
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_frames\netex_composite_frame_version.py", line 3, in <module>
    from netex.netex_framework.netex_frames.netex_common_frame_version import (
ImportError: cannot import name 'CommonVersionFrameStructure' from partially initialized module 'netex.netex_framework.netex_frames.netex_common_frame_version' (most likely due to a circular import) (C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\netex\netex_framework\netex_frames\netex_common_frame_version.py)

Process finished with exit code 1
```
Is this a problem in NeTEx we need to fix?

**Comment by skinkie** [comment]
To generate please use:

`xsdata generate -c netex.conf path/to/xsd/NeTEx_publication.xsd`

This is how the current netex folder is generated (it should not have to be updated, when not in XML Schema development).

**Comment by ue71603** [comment]
will retest
