### ISSUE TITLE
problem with trenord data  epip_db_to_db.py

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#90]
```

     {
    "block": "trenord",
    "scripts": [
        {"script": "clean_tmp", "args": ["./aux_test_processing"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_input/it-itc4-trenord_336.xml.gz ./aux_test_processing/netex-import.duckdb"]},
        {"script": "epip_db_to_db.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb"]},
        {"script": "epip_db_to_xml.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb ./aux_test_processing/milano-netex.xml"]},
        {"script": "aux_assertions.py", "args": ["./aux_test_input/general-netex-assertions.txt ./aux_test_processing/milano-netex.xml"]},
        {"script": "aux_netex_stats.py", "args": ["./aux_test_processing/milano-netex.xml"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_processing/milano-netex.xml ./aux_test_processing/netex-database.duckdb"]},
        {"script": "netex_db_to_gtfs.py", "args": ["./aux_test_processing/netex-database.duckdb ./aux_test_processing/milano-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["./aux_test_processing/milano-gtfs.zip ./aux_test_processing/milano-map.html routes"]}
        ]
  },

```
```

epip_scheduled_stop_point_memory
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 55, in <module>
    main(args.source, args.target)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\epip_db_to_db.py", line 43, in main
    epip_scheduled_stop_point_memory(target_database_file, target_database_file, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 96, in epip_scheduled_stop_point_memory
    with sqlite3.connect(write_database) as write_con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\epip.py", line 107, in epip_scheduled_stop_point_memory
    project_location_4326(ssp.location, generator_defaults)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\transformers\projection.py", line 28, in project_location_4326
    transformer = get_transformer_by_srs_name(location, 'urn:ogc:def:crs:EPSG::4326')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_transformer_by_srs_name() missing 1 required positional argument: 'generator_defaults'

``
[it-itc4-trenord_336.xml.gz](https://github.com/user-attachments/files/17010908/it-itc4-trenord_336.xml.gz)


`

**Comment by skinkie** [comment]
It is actually a source data projection. I agree this bug must be fixed, regardless of it.
```xml
                  <gml:pos srsName="ITA">45.697073 9.10725</gml:pos>
```

**Comment by ue71603** [comment]
Data problem
