### ISSUE TITLE
SOLEA (French NeTEx file)

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#94]
tried to fix part with: https://github.com/skinkie/reference/pull/81/commits/6e86dbfaa58353f01dbd281974414ce6f5a6e2a8

Next error:

```
*************
Starting script: netex_db_to_gtfs.py with ['./aux_test_processing/netex-database.duckdb', './aux_test_processing/solean-gtfs.zip']
C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Scripts\python.exe netex_db_to_gtfs.py ./aux_test_processing/netex-database.duckdb ./aux_test_processing/solean-gtfs.zip
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 182, in <module>
    convert(archive, args.netex)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 47, in convert
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 121, in convert
    CallsProfile.getCallsFromTimetabledPassingTimes(service_journey, service_journey_pattern)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\callsprofile.py", line 331, in getCallsFromTimetabledPassingTimes
    fare_scheduled_stop_point_ref_or_scheduled_stop_point_ref_or_scheduled_stop_point_view=ssp_refs[timetabled_passing_time.point_in_journey_pattern_ref.ref],
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ref'

Execution time: 13 seconds

Script netex_db_to_gtfs.py returned an error. Terminating the block of scripts: soleanetex

Process finished with exit code 0

```
 
[fluo-grand-est-sitram-netex.zip](https://github.com/user-attachments/files/17060092/fluo-grand-est-sitram-netex.zip)

sequence of commands:
```

   {
    "block": "soleanetex",
    "url": "https://transport.data.gouv.fr/datasets/fr-200052264-t0014-0000-1",
    "scripts": [
        {"script": "clean_tmp", "args": ["./aux_test_processing"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_input/fluo-grand-est-sitram-netex.zip ./aux_test_processing/netex-import.duckdb"]},
        {"script": "epip_db_to_db.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb"]},
        {"script": "epip_db_to_xml.py", "args": ["./aux_test_processing/netex-import.duckdb ./aux_test_processing/netex-database.duckdb ./aux_test_processing/solean-netex.xml"]},
        {"script": "aux_assertions.py", "args": ["./aux_test_input/general-netex-assertions.txt ./aux_test_processing/solean-netex.xml"]},
        {"script": "aux_netex_stats.py", "args": ["./aux_test_processing/solean-netex.xml"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_processing/solean-netex.xml ./aux_test_processing/netex-database.duckdb"]},
        {"script": "netex_db_to_gtfs.py", "args": ["./aux_test_processing/netex-database.duckdb ./aux_test_processing/solean-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["./aux_test_processing/solean-gtfs.zip ./aux_test_processing/solean-map.html all"]}
        ]
  },

```

Perhaps you have a detailled look, if the NeTEx is fine. I guess this gives us insight in the French way of doing things...

**Comment by skinkie** [comment]
This is just plainly invalid. There must be a relationship to the ServiceJourneyPattern. If we cannot even trust there is one, the id is missing, and we must hope that it is correctly ordered. No need to export NeTEx in this poor format.

```
                        <TimetabledPassingTime version="any">
                           <ArrivalTime>05:38:00</ArrivalTime>
                           <ArrivalDayOffset>0</ArrivalDayOffset>
                           <DepartureTime>05:38:00</DepartureTime>
                           <DepartureDayOffset>0</DepartureDayOffset>
                        </TimetabledPassingTime>
```
