### ISSUE TITLE
TimetabledPassingTime and no id/version

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#97]
at latest this results in an error when converting it to GTFS
```

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 182, in <module>
    convert(archive, args.netex)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 47, in convert
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 121, in convert
    CallsProfile.getCallsFromTimetabledPassingTimes(service_journey, service_journey_pattern)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\callsprofile.py", line 328, in getCallsFromTimetabledPassingTimes
    call = Call(id = timetabled_passing_time.id.replace(":TimetabledPassingTime:", ":Call:"),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'

```

and I added some code to add it aux_always_add_id_version.py. 
However, it seems a general problem that they don't do it and TimetabledPassingTime is never referenced. All the RefStructures are defined, but they are not included anywhere in the XSD.

So, perhaps we should add some code that creates unique id on  the fly, when the id/version is missing during netex_to_db.py?

**Comment by skinkie** [comment]
Can you include a source file?

**Comment by ue71603** [comment]
The source is here: https://github.com/MMTIS/QA/issues/5 referenced

I use a preprocessed file, where I already cleaned some problems (datasourceRef and the responsibilitySetRef) by removing them. Probably not the best idea ;-) 

[netex-export.zip](https://github.com/user-attachments/files/17083860/netex-export.zip)
Should I write a new program that generates stubs instead of removing them?

and then added new id to all TimetabledPassingTime.
[netex-export1.zip](https://github.com/user-attachments/files/17083861/netex-export1.zip)


Then I ran into a new problem:
```

Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 182, in <module>
    convert(archive, args.netex)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 47, in convert
    with sqlite3.connect(database) as con:
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_db_to_gtfs.py", line 121, in convert
    CallsProfile.getCallsFromTimetabledPassingTimes(service_journey, service_journey_pattern)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\callsprofile.py", line 331, in getCallsFromTimetabledPassingTimes
    fare_scheduled_stop_point_ref_or_scheduled_stop_point_ref_or_scheduled_stop_point_view=ssp_refs[timetabled_passing_time.point_in_journey_pattern_ref.ref],
                                                                                           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'it:apb:StopPointInJourneyPattern:224353.24a-1-0020209:'

```

at least in the XML it is there.

program sequence:

```
 {
    "block": "bolzano",
    "scripts": [
        {"script": "clean_tmp", "args": ["d:/aux_test_processing"]},
        {"script": "netex_to_db.py", "args": ["d:/aux_test_processing/netex-export1.xml d:/aux_test_processing/netex-import.duckdb"]},
        {"script": "netex_db_to_gtfs.py", "args": ["d:/aux_test_processing/netex-import.duckdb d:/aux_test_processing/bolzano-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["d:/aux_test_processing/bolzano-gtfs.zip d:/aux_test_processing/bolzano-map.html routes"]}
        ]
  },

```

**Comment by ue71603** [comment]
There are also a lot of warnings:
```

StopPlaceEntrance it:apb:StopPlaceEntrance:it-22024-97149: does not have a location or centroid.
StopPlaceEntrance it:apb:StopPlaceEntrance:it-22101-3281: does not have a location or centroid.
StopPlaceEntrance it:apb:StopPlaceEntrance:it-22101-3281: does not have a location or centroid.
```

Can I ignore them or are they also indicating a data problem?

**Comment by skinkie** [comment]
I think for going to GTFS it will then inherit the location from the StopPlace itself, but it is obviously a data problem. Why would someone make a StopPlaceEntrance, without telling where it is?

**Comment by ue71603** [comment]
I will add the problem with the StopPlaceEntrance to my complaints to STA.

**Comment by ue71603** [comment]
aux_always_add_id_version.py addresses the Timetabledproblem.
